spring:

# MariaDB
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://cabon.cdspom5j0apx.ap-northeast-2.rds.amazonaws.com:3306/dev
      username: admin
      password: adminadmin

 # H2
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true


